### PR TITLE
bug-fix: "the remote archive doesn't match the expected checksums"

### PR DESCRIPTION
**Pull request by chris-straka**
When I run `yarn install` on a new project, I get multiple errors saying "the remote archive does not match the expected checksum"

image

The [YN0018 error](https://yarnpkg.com/advanced/error-codes#yn0018---cache_checksum_mismatch) can be fixed by setting the default checksum behavior (which you can set in the `.yarnrc.yml` file). I think the options were `ignore`, `throw` and `update`. The last one (`update`) made the most sense to me.

image

Thank you for this template and have a nice day!

### CODE REVIEW

**Comment by ShravanSunder** [comment]
@Chris56974 would this be a security issue if we allow it to change checksome?  also would it cause a lot of unnecessary changes in future PRs as the lock file is constantly change?

**Comment by chris-straka** [comment]
Good question, I'm not sure. You bring up a good point. From reading [this comment by arcanis](https://github.com/yarnpkg/berry/issues/1142#issuecomment-607272809) it sounds like updating the checksums once is all that's needed. Updating checksums continuously is probably not desirable. It might be better to leave a comment in the readme letting people know that they might have to use `YARN_CHECKSUM_BEHAVIOR=update yarn` on the first install.

When it comes to security, again I'm not entirely sure haha. When I read [this blog article](https://debricked.com/blog/fixing-security-vulnerabilities-yarn/), they say "While [checksum validation] is not a major concern as most npm modules are downloaded through a TLS/SSL encrypted connection, it still has its cases. You might be downloading from your company’s local npm registry, or you might for some reason be forced to use a pure HTTP, unencrypted connection. A targeted attack could easily use such an opportunity to introduce a more serious backdoor into your software. A bigger concern is the increased attack surface area inherent in using any third-party modules".

So I'll defer to your judgement, it's hard for me to say. Enjoy the rest of your weekend 🙂

**Comment by ShravanSunder** [comment]
> Good question, I'm not sure. You bring up a good point. From reading [this comment by arcanis](https://github.com/yarnpkg/berry/issues/1142#issuecomment-607272809) it sounds like updating the checksums once is all that's needed. Updating checksums continuously is probably not desirable. It might be better to leave a comment in the readme letting people know that they might have to use `YARN_CHECKSUM_BEHAVIOR=update yarn` on the first install.
> 
> When it comes to security, again I'm not entirely sure haha. When I read [this blog article](https://debricked.com/blog/fixing-security-vulnerabilities-yarn/), they say "While [checksum validation] is not a major concern as most npm modules are downloaded through a TLS/SSL encrypted connection, it still has its cases. You might be downloading from your company’s local npm registry, or you might for some reason be forced to use a pure HTTP, unencrypted connection. A targeted attack could easily use such an opportunity to introduce a more serious backdoor into your software. A bigger concern is the increased attack surface area inherent in using any third-party modules".
> 
> So I'll defer to your judgement, it's hard for me to say. Enjoy the rest of your weekend 🙂

Thanks for the details. I’ll lean towards better docs and trouble shooting. We are making docs in docusaurus so it might be easier to discover.

**Comment by marty-mcgee** [comment]
I am able to get yarn install to work by making the following change to the root .yarnrc.yml file..
`checksumBehavior: "update"`

See this primary link for more details: 
[yarnrc checksumBehavior](https://yarnpkg.com/configuration/yarnrc#checksumBehavior)
Allowed values are "throw" (default), "update", and "ignore".

..and this supportive link:
[YN0018 - CACHE_CHECKSUM_MISMATCH (YARN_CHECKSUM_BEHAVIOR)](https://yarnpkg.com/advanced/error-codes#yn0018---cache_checksum_mismatch)

My complete .yarnrc.yml code is this:
```
checksumBehavior: "update"
nmHoistingLimits: workspaces
nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
yarnPath: .yarn/releases/yarn-3.1.0.cjs
```

**Comment by ShravanSunder** [comment]
@Chris56974 @Chris-Kag i've set it to checksum ignore.  i think that should fix it for now

**Pull request closed without merging**
